### ISSUE TITLE
APIs not working

### ISSUE THREAD

**Issue by thememehub** [gregrickaby/nextjs-github-pages#12]
The only problem I can see with Github pages, we can not use API in Github. we can call API in getStaticProps but all the nextjs API is 404.

https://gregrickaby.github.io/nextjs-github-pages/api/hello

Do you have any fix for this?

**Comment by gregrickaby** [comment]
@thememehub Thanks for the question.

Because we have to use `next export` to build the app, Next.js disables "dynamic" features like API Routes, `next/image`, and Incremental Static Regeneration to name a few. ☹️  

Unfortunately, hosting Next.js anywhere other than Vercel (or more specifically, anywhere that doesn't support starting serverless functions via `next start`) will cause Next.js to be a bit limited.

You can learn more here:

- https://nextjs.org/docs/advanced-features/static-html-export
- https://nextjs.org/docs/api-routes/introduction#caveats
- https://github.com/vercel/next.js/discussions/28216#discussioncomment-1203150
